USE [PuraVidaStore]
GO

/*Primero Inserta las categor[ias*/
-- Inserta las categorías solo si no existen
IF NOT EXISTS (SELECT 1 FROM[dbo].[Bodegas] WHERE bdgDescripcion = 'Secundaria')
BEGIN
    INSERT INTO [dbo].[Bodegas] ([bdgDescripcion],[bdgVisible])
    VALUES ('Secundaria', 1);
END

/*Primero Inserta las categor[ias*/
-- Inserta las categorías solo si no existen
IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'COSMÉTICOS')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('COSMÉTICOS', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'ELECTRÓNICOS')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('ELECTRÓNICOS', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'HOGAR')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('HOGAR', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'INFANTIL')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('INFANTIL', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'JOYERÍA')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('JOYERÍA', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'MASCOTAS')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('MASCOTAS', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'RELOJES')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('RELOJES', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'SEGURIDAD')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('SEGURIDAD', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'USO PERSONAL')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('USO PERSONAL', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'VARIOS')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('VARIOS', 1);
END

IF NOT EXISTS (SELECT 1 FROM [dbo].[TipoProducto] WHERE [TppDescripcion] = 'VESTIMENTA')
BEGIN
    INSERT INTO [dbo].[TipoProducto] ([TppDescripcion], [TppVisible])
    VALUES ('VESTIMENTA', 1);
END
GO


IF OBJECT_ID('tempdb..#Productos') IS NOT NULL
    DROP TABLE #Productos;
go

CREATE TABLE #Productos (
    Categoria VARCHAR(50),
    DescripcionArticulo VARCHAR(100)
);

INSERT INTO #Productos (Categoria, DescripcionArticulo) VALUES
('COSMÉTICOS', 'BROCHAS 24 UNIDADES'),
('COSMÉTICOS', 'BROCHAS EN ESTUCHE 24 UNIDADES'),
('COSMÉTICOS', 'BROCHAS EN ESTUCHE PROF 24 UNIDADES'),
('COSMÉTICOS', 'BROCHAS EN TARRO 11 UNIDADES'),
('COSMÉTICOS', 'BROCHAS ESTUCHE 32 UNIDADES'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES 10 UNIDADES'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES 8 UNIDADES'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES ESCARCHA'),
('COSMÉTICOS', 'BROCHAS UNICORNIO AZUL 10 UNIDADES'),
('COSMÉTICOS', 'BROCHAS UNICORNIO 10 UNIDADES'),
('COSMÉTICOS', 'MAQUILLAJE SOMBRE 180 COLORES'),
('ELECTRÓNICOS', 'AUDIFINOS DIADEMAM FB-K1'),
('ELECTRÓNICOS', 'AUDÍFONOS CON CABLE EDXPRO'),
('ELECTRÓNICOS', 'BATERÍA PORTÁTIL PARA CELULAR'),
('HOGAR', 'CUADROS LED DE BATMAN'),
('HOGAR', 'LAMPARA LED PARA PARED'),
('HOGAR', 'LAMPARA PARA MOSQUITOS'),
('INFANTIL', 'BULTOS DE NIÑA DONA'),
('INFANTIL', 'CÁMARAS DE JUGUETE NIÑAS'),
('INFANTIL', 'DIADEMA DE BARBIE NIÑA'),
('INFANTIL', 'DISFRAZ DE DINOSAURIO'),
('INFANTIL', 'JUGUETE INFANTIL SMALL DUCK'),
('INFANTIL', 'MUÑERO SPIDERMAN'),
('INFANTIL', 'TIENDA DE ACAMPAR'),
('JOYERÍA', 'ANILLO AJUSTABLE PROMESA'),
('JOYERÍA', 'ANILLO ESTRELLA AZUL'),
('JOYERÍA', 'ANILLO LEDY DI (AJUSTABLE)'),
('JOYERÍA', 'ARETES ABEJA'),
('JOYERÍA', 'ARETES ABEJA Y FLOR PLATA 925'),
('JOYERÍA', 'ARETES CONEJO'),
('JOYERÍA', 'ARETES CONEJO ENCHAPADO ORO 14K'),
('JOYERÍA', 'ARETES LEDY DI'),
('JOYERÍA', 'ARETES MASCOTA'),
('JOYERÍA', 'ARETES TULIPAN ENCHAPADO ORO 14K'),
('JOYERÍA', 'ARETES TULIPAN ROSA ENCHAPADO ORO 14K'),
('JOYERÍA', 'ARGOLLAS CORAZON'),
('JOYERÍA', 'CADENA CABALLERO EN ACERO'),
('JOYERÍA', 'COLLAR ABEJA'),
('JOYERÍA', 'COLLAR CEREZO'),
('JOYERÍA', 'COLLAR CORAZON AZUL'),
('JOYERÍA', 'COLLAR FLOR MARGARRITA'),
('JOYERÍA', 'COLLAR FRESA-PLATA 925'),
('JOYERÍA', 'COLLAR LEDY DI'),
('JOYERÍA', 'COLLAR LUCIRNAGA LUMINOSO'),
('JOYERÍA', 'COLLAR MARGARITA- ABEJA 0RO 14K'),
('JOYERÍA', 'COLLAR MASCOTA'),
('JOYERÍA', 'COLLAR MASCOTA ENCHAPADO ORO 14K'),
('JOYERÍA', 'COLLAR TULIPAN ENCHAPADO ORO 14K'),
('JOYERÍA', 'PULSERA CABALLERO EN ACERO'),
('JOYERÍA', 'PULSERA HELLO KITTY - ENCHAPADO ORO 14K'),
('JOYERÍA', 'PULSERA HELLO KITTY ENCHAPADO PLATA 925'),
('JOYERÍA', 'PULSERA MARGARITA-PLATA 925'),
('JOYERÍA', 'PULSERA PLATA CORAZON ELASTICA'),
('JOYERÍA', 'PULSERA ROSA PLATA 925'),
('MASCOTAS', 'MANGUERA PARA PERROS'),
('RELOJES', 'RELOJ DIGITAL HOMBRE SKMEI'),
('RELOJES', 'RELOJ HOMBRE SPIDERMAN CUERO'),
('RELOJES', 'RELOJ INFANTIL CON MUSICA'),
('RELOJES', 'RELOJ MUJER BRAZALETE ACERO HELLO KITTY'),
('RELOJES', 'RELOJ MUJER CON PULSERA HELLO KITTY'),
('RELOJES', 'RELOJ MUJER STICH ACERO'),
('RELOJES', 'RELOJ MUJER STICH CUERO'),
('SEGURIDAD', 'CÁMARA SEGURIDAD WI-FI EXTERIOR E INTERIOR'),
('SEGURIDAD', 'CÁMARA SEGURIDAD WI-FI SOLAR'),
('USO PERSONAL', 'CEPILLO DE BAÑO'),
('USO PERSONAL', 'CEPILLO FACIAL'),
('USO PERSONAL', 'COLAS DE CABELLO NIÑA'),
('USO PERSONAL', 'CORRECTO DE JUANETE'),
('USO PERSONAL', 'CREMAS KARSELL CABELLO'),
('USO PERSONAL', 'DEPILADOR LASER'),
('USO PERSONAL', 'GUANTE DE COMPRESIÓN'),
('USO PERSONAL', 'KIT DEPILADOR LASER Y DEPILADOR MANUAL Y CEPILLA FACIAL'),
('USO PERSONAL', 'MASAJEADOR FACIAL'),
('USO PERSONAL', 'MEDIDOR DE PRESIÓN ARTERIAL'),
('VARIOS', 'LONA PARA PLAYA'),
('VARIOS', 'SOPORTE DE BICICLETA'),
('VESTIMENTA', 'CHAQUETA BOB ESPONJA CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA CAPUCHA SNOOPY AMIGOS CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA CAPUCHA SNOOPY CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA GARFRIEL CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA HELLO KITTY CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA LOONEY TUNES CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA MICKEY Y MINI LONDRES CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE VARIOS CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE COCA COLA CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE NEGRA CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE NEGRA Y GRIS CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA MINI MAUSE CELESTE CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA OSOS ESCANDALOSOS CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA RUGRATS AMIGOS CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA SONIC CORTA VIENTOS NIÑOS 2 A 8 AÑOS'),
('VESTIMENTA', 'CHAQUETA SPIDERMAN CORTA VIENTOS NIÑOS 2 A 12 AÑOS'),
('VESTIMENTA', 'CHAQUETA SPIDERMAN CORTA VIENTOS NIÑOS 2 A 8 AÑOS'),
('VESTIMENTA', 'CHAQUETA STITCH- CELESTE CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA STITCH- ROSA CORTA VIENTOS'),
('VESTIMENTA', 'CHAQUETA STITCH- TORNASOL CORTA VIENTOS'),
('VESTIMENTA', 'SUETER ANGEL CAPUCHA CON DETALLE'),
('VESTIMENTA', 'SUETER ARISTOCATS NIÑA 6 A 12 AÑOS'),
('VESTIMENTA', 'SUETER BUGS BUNNY'),
('VESTIMENTA', 'SUETER CAPUCHA SNOOPY ALGODÓN'),
('VESTIMENTA', 'SUETER CARLITOS OVERSIZE'),
('VESTIMENTA', 'SUETER GOOFY NINOS 6 A 12 AÑOS'),
('VESTIMENTA', 'SUETER HELLO CHARLI OVERSIZE'),
('VESTIMENTA', 'SUETER HELLO KITTY CAPUCHA CON DETALLE'),
('VESTIMENTA', 'SUETER HELLO KITTY OVERSIZE'),
('VESTIMENTA', 'SUETER HELLO KITTY PELUDITO'),
('VESTIMENTA', 'SUETER HELLO KITTY PERSONAJES OVERSIZE'),
('VESTIMENTA', 'SUETER HELLO PATO DONALD OVERSIZE'),
('VESTIMENTA', 'SUETER HELLO STITCH OVERSIZE'),
('VESTIMENTA', 'SUETER JIGGLYPUFF CAPUCHA CON DETALLE'),
('VESTIMENTA', 'SUETER KUROMORI CAPUCHA CON DETALLE'),
('VESTIMENTA', 'SUETER KUROMORI OVERSIZE'),
('VESTIMENTA', 'SUETER MAFALDA CAPUCHA CON DETALLE'),
('VESTIMENTA', 'SUETER MAFALDA PELUDITO'),
('VESTIMENTA', 'SUETER MELODI CAPUCHA CON DETALLE'),
('VESTIMENTA', 'SUETER MICKEY MOUSE HISTORIA'),
('VESTIMENTA', 'SUETER MICKEY MOUSE HISTORIA NINOS 4 A 12 AÑOS'),
('VESTIMENTA', 'SUETER MICKEY MOUSE PELUDITO'),
('VESTIMENTA', 'SUETER MICKEY MOUSE PELUDITO VARIOS'),
('VESTIMENTA', 'SUETER MICKEY MOUSE SALUDOS'),
('VESTIMENTA', 'SUETER MICKEY MOUSE SIN CAPUCHA'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELIDITA'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELIDITA LAZO ROJO'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELIDITA MORADA'),
('VESTIMENTA', 'SUETER MINI MOUSE NIÑA 4 A 12 AÑOS'),
('VESTIMENTA', 'SUETER MINNI OVERSIZE'),
('VESTIMENTA', 'SUETER MOSTER IN OVERSIZE'),
('VESTIMENTA', 'SUETER NARUTO'),
('VESTIMENTA', 'SUETER OSOS ESCANDALOSOS ALGODÓN'),
('VESTIMENTA', 'SUETER OSOS ESCANDALOSOS NIÑOS 2 A 8 AÑOS'),
('VESTIMENTA', 'SUETER PANTERA ROSA PELUDITO'),
('VESTIMENTA', 'SUETER PIKACHU CAPUCHA CON DETALLE'),
('VESTIMENTA', 'SUETER RUGRATS AMIGOS'),
('VESTIMENTA', 'SUETER RUGRATS AMIGOS NINOS 6 A 12 AÑOS'),
('VESTIMENTA', 'SUETER RUGRATS ANGELICA'),
('VESTIMENTA', 'SUETER RUGRATS ANGELICA CAPUCHA PELUDITA'),
('VESTIMENTA', 'SUETER RUGRATS CARLITOS'),
('VESTIMENTA', 'SUETER STITCH CAPUCHA ALGODÓN'),
('VESTIMENTA', 'SUETER STITCH CUELLO REDONDO'),
('VESTIMENTA', 'SUETER STITCH PELUDITO'),
('VESTIMENTA', 'SUETER WINNIE POOH CAPUCHA PELIDITA'),
('VESTIMENTA', 'SUTER HELLO KITTY PELUDITO NEGRO'),
('VESTIMENTA', 'SUTER TOM Y JERRY');
GO

DECLARE @contador INT = 1;
DECLARE @totalProductos INT;

-- Obtener el total de productos en la tabla temporal
SELECT @totalProductos = COUNT(1) FROM #Productos;

WHILE @contador <= @totalProductos
BEGIN
    DECLARE @PrdNombre VARCHAR(50);
    DECLARE @Categoria VARCHAR(50);
    DECLARE @IdCategoria INT;

    -- Obtener los valores de la tabla temporal
    SELECT @PrdNombre = DescripcionArticulo, 
           @Categoria = Categoria,
		   @IdCategoria = (SELECT top(1) TppId FROM [dbo].[TipoProducto] WHERE TppDescripcion = Categoria)
    FROM #Productos
    ORDER BY (SELECT NULL) -- Ordenar por cualquier columna o ninguna

    OFFSET @contador - 1 ROWS FETCH NEXT 1 ROWS ONLY; -- Obtener el producto actual

	    -- Verificar si el producto ya existe antes de insertar
    IF NOT EXISTS (SELECT 1 FROM [dbo].[Productos] WHERE PrdNombre = @PrdNombre AND PrdIdTipoProducto = @IdCategoria)
    BEGIN



	    INSERT INTO [dbo].[Productos]
           (
			   [PrdNombre]
			   ,[PrdPrecioVentaMayorista]
			   ,[PrdPrecioVentaMinorista]
			   ,[PrdCodigo]
			   ,[PrdUnidadesMinimas]
			   ,[PrdIdTipoProducto]
			   ,[PrdCodigoProvedor]
			   ,[PdrVisible]
			   ,[PdrFoto]
			   ,[PdrTieneExistencias]
		   )
     VALUES
           (@PrdNombre
           ,1
           ,1
           ,NULL
           ,0
           , (SELECT TOP(1) TppId FROM [dbo].[TipoProducto]  WHERE TppDescripcion = @Categoria)
           ,NULL
           ,''
           ,NULL
           ,1
           );





	UPDATE P
		SET P.[PrdCodigo] = CONCAT('PVS',@IdCategoria,'C',P.PrdId)
	FROM [dbo].[Productos] P
		INNER JOIN TipoProducto T ON P.[PrdIdTipoProducto] = T.[TppId] 
		WHERE 
			T.TppDescripcion = @Categoria
			AND P.PrdNombre = @PrdNombre; 
	END

		SET @contador = @contador + 1; -- Incrementar el contador
END
Go

-- Verifica y elimina la tabla temporal si existe
IF OBJECT_ID('tempdb..#Inventario') IS NOT NULL
    DROP TABLE #Inventario;

-- Crea la tabla temporal
CREATE TABLE #Inventario (
    Categoria NVARCHAR(50),
    DescripcionArticulo NVARCHAR(100),
    SumaCantidadTienda INT,
    Sitio NVARCHAR(50)
);

-- Inserta los datos
INSERT INTO #Inventario (Categoria, DescripcionArticulo, SumaCantidadTienda, Sitio) VALUES
('COSMÉTICOS', 'BROCHAS 24 UNIDADES', 42, 'Tienda'),
('COSMÉTICOS', 'BROCHAS EN ESTUCHE 24 UNIDADES', 8, 'Tienda'),
('COSMÉTICOS', 'BROCHAS EN ESTUCHE PROF 24 UNIDADES', 2, 'Tienda'),
('COSMÉTICOS', 'BROCHAS EN TARRO 11 UNIDADES', 14, 'Tienda'),
('COSMÉTICOS', 'BROCHAS ESTUCHE 32 UNIDADES', 18, 'Tienda'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES 10 UNIDADES', 7, 'Tienda'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES 8 UNIDADES', 10, 'Tienda'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES ESCARCHA', 49, 'Tienda'),
('COSMÉTICOS', 'BROCHAS UNICORNIO AZUL 10 UNIDADES', 12, 'Tienda'),
('COSMÉTICOS', 'BROCHAS UNICORNIO 10 UNIDADES', 13, 'Tienda'),
('COSMÉTICOS', 'MAQUILLAJE SOMBRE 180 COLORES', NULL, 'Bodega'),
('ELECTRÓNICOS', 'AUDIFINOS DIADEMAM FB-K1', 9, 'Tienda'),
('ELECTRÓNICOS', 'AUDÍFONOS CON CABLE EDXPRO', 9, 'Tienda'),
('ELECTRÓNICOS', 'BATERÍA PORTÁTIL PARA CELULAR', NULL, 'Bodega'),
('HOGAR', 'CUADROS LED DE BATMAN', 3, 'Tienda'),
('HOGAR', 'LAMPARA LED PARA PARED', 45, 'Tienda'),
('HOGAR', 'LAMPARA PARA MOSQUITOS', 6, 'Tienda'),
('INFANTIL', 'BULTOS DE NIÑA DONA', 3, 'Tienda'),
('INFANTIL', 'CÁMARAS DE JUGUETE NIÑAS', 10, 'Tienda'),
('INFANTIL', 'DIADEMA DE BARBIE NIÑA', 10, 'Tienda'),
('INFANTIL', 'DISFRAZ DE DINOSAURIO', 16, 'Tienda'),
('INFANTIL', 'JUGUETE INFANTIL SMALL DUCK', 6, 'Tienda'),
('INFANTIL', 'MUÑERO SPIDERMAN', 40, 'Tienda'),
('INFANTIL', 'TIENDA DE ACAMPAR', 2, 'Tienda'),
('JOYERÍA', 'ANILLO AJUSTABLE PROMESA', NULL, 'Bodega'),
('JOYERÍA', 'ANILLO ESTRELLA AZUL', NULL, 'Bodega'),
('JOYERÍA', 'ANILLO LEDY DI (AJUSTABLE)', NULL, 'Bodega'),
('JOYERÍA', 'ARETES ABEJA', NULL, 'Bodega'),
('JOYERÍA', 'ARETES ABEJA Y FLOR PLATA 925', NULL, 'Bodega'),
('JOYERÍA', 'ARETES CONEJO', NULL, 'Bodega'),
('JOYERÍA', 'ARETES CONEJO ENCHAPADO ORO 14K', NULL, 'Bodega'),
('JOYERÍA', 'ARETES LEDY DI', NULL, 'Bodega'),
('JOYERÍA', 'ARETES MASCOTA', NULL, 'Bodega'),
('JOYERÍA', 'ARETES TULIPAN ENCHAPADO ORO 14K', NULL, 'Bodega'),
('JOYERÍA', 'ARETES TULIPAN ROSA ENCHAPADO ORO 14K', NULL, 'Bodega'),
('JOYERÍA', 'ARGOLLAS CORAZON', NULL, 'Bodega'),
('JOYERÍA', 'CADENA CABALLERO EN ACERO', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR ABEJA', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR CEREZO', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR CORAZON AZUL', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR FLOR MARGARRITA', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR FRESA-PLATA 925', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR LEDY DI', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR LUCIRNAGA LUMINOSO', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR MARGARITA- ABEJA 0RO 14K', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR MASCOTA', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR MASCOTA ENCHAPADO ORO 14K', NULL, 'Bodega'),
('JOYERÍA', 'COLLAR TULIPAN ENCHAPADO ORO 14K', NULL, 'Bodega'),
('JOYERÍA', 'PULSERA CABALLERO EN ACERO', NULL, 'Bodega'),
('JOYERÍA', 'PULSERA HELLO KITTY - ENCHAPADO ORO 14K', NULL, 'Bodega'),
('JOYERÍA', 'PULSERA HELLO KITTY ENCHAPADO PLATA 925', NULL, 'Bodega'),
('JOYERÍA', 'PULSERA MARGARITA-PLATA 925', NULL, 'Bodega'),
('JOYERÍA', 'PULSERA PLATA CORAZON ELASTICA', NULL, 'Bodega'),
('JOYERÍA', 'PULSERA ROSA PLATA 925', NULL, 'Bodega'),
('MASCOTAS', 'MANGUERA PARA PERROS', 5, 'Tienda'),
('RELOJES', 'RELOJ DIGITAL HOMBRE SKMEI', 10, 'Tienda'),
('RELOJES', 'RELOJ HOMBRE SPIDERMAN CUERO', 12, 'Tienda'),
('RELOJES', 'RELOJ INFANTIL CON MUSICA', 32, 'Tienda'),
('RELOJES', 'RELOJ MUJER BRAZALETE ACERO HELLO KITTY', 17, 'Tienda'),
('RELOJES', 'RELOJ MUJER CON PULSERA HELLO KITTY', 5, 'Tienda'),
('RELOJES', 'RELOJ MUJER STICH ACERO', 6, 'Tienda'),
('RELOJES', 'RELOJ MUJER STICH CUERO', 18, 'Tienda'),
('SEGURIDAD', 'CÁMARA SEGURIDAD WI-FI EXTERIOR E INTERIOR', NULL, 'Bodega'),
('SEGURIDAD', 'CÁMARA SEGURIDAD WI-FI SOLAR', NULL, 'Bodega'),
('USO PERSONAL', 'CEPILLO DE BAÑO', 6, 'Tienda'),
('USO PERSONAL', 'CEPILLO FACIAL', 4, 'Tienda'),
('USO PERSONAL', 'COLAS DE CABELLO NIÑA', NULL, 'Bodega'),
('USO PERSONAL', 'CORRECTOR DE JUANETE', 28, 'Tienda'),
('USO PERSONAL', 'CREMAS KARSELL CABELLO', 12, 'Tienda'),
('USO PERSONAL', 'DEPILADOR LASER', NULL, 'Bodega'),
('USO PERSONAL', 'GUANTE DE COMPRESIÓN', 29, 'Tienda'),
('USO PERSONAL', 'KIT DEPILADOR LASER Y DEPILADOR MANUAL Y CEPILLO FACIAL', 5, 'Tienda'),
('USO PERSONAL', 'MASAJEADOR FACIAL', NULL, 'Bodega'),
('USO PERSONAL', 'MEDIDOR DE PRESIÓN ARTERIAL', 9, 'Tienda'),
('VARIOS', 'LONA PARA PLAYA', 23, 'Tienda'),
('VARIOS', 'SOPORTE DE BICICLETA', 15, 'Tienda'),
('VESTIMENTA', 'CHAQUETA BOB ESPONJA CORTA VIENTOS', 3, 'Tienda'),
('VESTIMENTA', 'CHAQUETA CAPUCHA SNOOPY AMIGOS CORTA VIENTOS', 2, 'Tienda'),
('VESTIMENTA', 'CHAQUETA CAPUCHA SNOOPY CORTA VIENTOS', 1, 'Tienda'),
('VESTIMENTA', 'CHAQUETA GARFRIEL CORTA VIENTOS', 7, 'Tienda'),
('VESTIMENTA', 'CHAQUETA HELLO KITTY CORTA VIENTOS', NULL, 'Bodega'),
('VESTIMENTA', 'CHAQUETA LOONEY TUNES CORTA VIENTOS', 4, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MICKEY Y MINI LONDRES CORTA VIENTOS', NULL, 'Bodega'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE VARIOS CORTA VIENTOS', 1, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE COCA COLA CORTA VIENTOS', 4, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE NEGRA CORTA VIENTOS', NULL, 'Bodega'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE NEGRA Y GRIS CORTA VIENTOS', NULL, 'Bodega'),
('VESTIMENTA', 'CHAQUETA MINI MAUSE CELESTE CORTA VIENTOS', NULL, 'Bodega'),
('VESTIMENTA', 'CHAQUETA OSOS ESCANDALOSOS CORTA VIENTOS', 4, 'Tienda'),
('VESTIMENTA', 'CHAQUETA RUGRATS AMIGOS CORTA VIENTOS', 4, 'Tienda'),
('VESTIMENTA', 'CHAQUETA SONIC CORTA VIENTOS NIÑOS 2 A 8 AÑOS', 1, 'Tienda'),
('VESTIMENTA', 'CHAQUETA SPIDERMAN CORTA VIENTOS NIÑOS 2 A 12 AÑOS', NULL, 'Bodega'),
('VESTIMENTA', 'CHAQUETA SPIDERMAN CORTA VIENTOS NIÑOS 2 A 8 AÑOS', 1, 'Tienda'),
('VESTIMENTA', 'CHAQUETA STITCH- CELESTE CORTA VIENTOS', 1, 'Tienda'),
('VESTIMENTA', 'CHAQUETA STITCH- ROSA CORTA VIENTOS', 2, 'Tienda'),
('VESTIMENTA', 'CHAQUETA STITCH- TORNASOL CORTA VIENTOS', 2, 'Tienda'),
('VESTIMENTA', 'SUETER ANGEL CAPUCHA CON DETALLE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER ARISTOCATS NIÑA 6 A 12 AÑOS', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER BUGS BUNNY', 2, 'Tienda'),
('VESTIMENTA', 'SUETER CAPUCHA SNOOPY ALGODÓN', 1, 'Tienda'),
('VESTIMENTA', 'SUETER CARLITOS OVERSIZE', 1, 'Tienda'),
('VESTIMENTA', 'SUETER GOOFY NINOS 6 A 12 AÑOS', 1, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO CHARLI OVERSIZE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO KITTY CAPUCHA CON DETALLE', 1, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO KITTY OVERSIZE', 3, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO KITTY PELUDITO', 6, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO KITTY PERSONAJES OVERSIZE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO PATO DONALD OVERSIZE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO STITCH OVERSIZE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER JIGGLYPUFF CAPUCHA CON DETALLE', 1, 'Tienda'),
('VESTIMENTA', 'SUETER KUROMORI CAPUCHA CON DETALLE', 1, 'Tienda'),
('VESTIMENTA', 'SUETER KUROMORI OVERSIZE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER MAFALDA CAPUCHA CON DETALLE', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER MAFALDA PELUDITO', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER MELODI CAPUCHA CON DETALLE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE HISTORIA', 1, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE HISTORIA NINOS 4 A 12 AÑOS', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER MICKEY MOUSE PELUDITO', 2, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE PELUDITO VARIOS', 1, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE SALUDOS', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER MICKEY MOUSE SIN CAPUCHA', 4, 'Tienda'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELIDITA', 1, 'Tienda'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELIDITA LAZO ROJO', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELIDITA MORADA', 5, 'Tienda'),
('VESTIMENTA', 'SUETER MINI MOUSE NIÑA 4 A 12 AÑOS', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER MINNI OVERSIZE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER MOSTER IN OVERSIZE', 1, 'Tienda'),
('VESTIMENTA', 'SUETER NARUTO', 2, 'Tienda'),
('VESTIMENTA', 'SUETER OSOS ESCANDALOSOS ALGODÓN', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER OSOS ESCANDALOSOS NIÑOS 2 A 8 AÑOS', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER PANTERA ROSA PELUDITO', 2, 'Tienda'),
('VESTIMENTA', 'SUETER PIKACHU CAPUCHA CON DETALLE', 2, 'Tienda'),
('VESTIMENTA', 'SUETER RUGRATS AMIGOS', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER RUGRATS AMIGOS NINOS 6 A 12 AÑOS', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER RUGRATS ANGELICA', 3, 'Tienda'),
('VESTIMENTA', 'SUETER RUGRATS ANGELICA CAPUCHA PELUDITA', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER RUGRATS CARLITOS', 3, 'Tienda'),
('VESTIMENTA', 'SUETER STITCH CAPUCHA ALGODÓN', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER STITCH CUELLO REDONDO', 2, 'Tienda'),
('VESTIMENTA', 'SUETER STITCH PELUDITO', NULL, 'Bodega'),
('VESTIMENTA', 'SUETER WINNIE POOH CAPUCHA PELIDITA', NULL, 'Bodega'),
('VESTIMENTA', 'SUTER HELLO KITTY PELUDITO NEGRO', 2, 'Tienda'),
('VESTIMENTA', 'SUTER TOM Y JERRY', 1, 'Tienda');

go

INSERT INTO  #Inventario (Categoria, DescripcionArticulo, SumaCantidadTienda, Sitio) VALUES
('COSMÉTICOS', 'BROCHAS 24 UNIDADES', 42, 'Bodega'),
('COSMÉTICOS', 'BROCHAS EN ESTUCHE 24 UNIDADES', 8, 'Bodega'),
('COSMÉTICOS', 'BROCHAS EN ESTUCHE PROF 24 UNIDADES', 2, 'Bodega'),
('COSMÉTICOS', 'BROCHAS EN TARRO 11 UNIDADES', 52, 'Bodega'),
('COSMÉTICOS', 'BROCHAS ESTUCHE 32 UNIDADES', 18, 'Bodega'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES 10 UNIDADES', 7, 'Bodega'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES 8 UNIDADES', 10, 'Bodega'),
('COSMÉTICOS', 'BROCHAS PROFECIONALES ESCARCHA', 49, 'Bodega'),
('COSMÉTICOS', 'BROCHAS UNICORNIO AZUL 10 UNIDADES', 12, 'Bodega'),
('COSMÉTICOS', 'BROCHAS UNICORNIO 10 UNIDADES', 13, 'Bodega'),
('COSMÉTICOS', 'MAQUILLAJE SOMBRE 180 COLORES', 2, 'Bodega'),
('ELECTRÓNICOS', 'AUDIFINOS DIADEMAM FB-K1', 9, 'Bodega'),
('ELECTRÓNICOS', 'AUDÍFONOS CON CABLE EDXPRO', 9, 'Bodega'),
('ELECTRÓNICOS', 'BATERÍA PORTÁTIL PARA CELULAR', 11, 'Bodega'),
('HOGAR', 'CUADROS LED DE BATMAN', 3, 'Bodega'),
('HOGAR', 'LAMPARA LED PARA PARED', 45, 'Bodega'),
('HOGAR', 'LAMPARA PARA MOSQUITOS', 29, 'Bodega'),
('INFANTIL', 'BULTOS DE NIÑA DONA', 25, 'Bodega'),
('INFANTIL', 'CÁMARAS DE JUGUETE NIÑAS', 10, 'Bodega'),
('INFANTIL', 'DIADEMA DE BARBIE NIÑA', 48, 'Bodega'),
('INFANTIL', 'DISFRAZ DE DINOSAURIO', 16, 'Bodega'),
('INFANTIL', 'JUGUETE INFANTIL SMALL DUCK', 14, 'Bodega'),
('INFANTIL', 'MUÑERO SPIDERMAN', 40, 'Bodega'),
('INFANTIL', 'TIENDA DE ACAMPAR', 10, 'Bodega'),
('JOYERÍA', 'ANILLO AJUSTABLE PROMESA', 5, 'Bodega'),
('JOYERÍA', 'ANILLO ESTRELLA AZUL', 4, 'Bodega'),
('JOYERÍA', 'ANILLO LEDY DI (AJUSTABLE)', NULL, 'Tienda'),
('JOYERÍA', 'ARETES ABEJA', NULL, 'Tienda'),
('JOYERÍA', 'ARETES ABEJA Y FLOR PLATA 925', 5, 'Bodega'),
('JOYERÍA', 'ARETES CONEJO', 5, 'Bodega'),
('JOYERÍA', 'ARETES CONEJO ENCHAPADO ORO 14K', 5, 'Bodega'),
('JOYERÍA', 'ARETES LEDY DI', NULL, 'Tienda'),
('JOYERÍA', 'ARETES MASCOTA', 5, 'Bodega'),
('JOYERÍA', 'ARETES TULIPAN ENCHAPADO ORO 14K', 5, 'Bodega'),
('JOYERÍA', 'ARETES TULIPAN ROSA ENCHAPADO ORO 14K', 5, 'Bodega'),
('JOYERÍA', 'ARGOLLAS CORAZON', 7, 'Bodega'),
('JOYERÍA', 'CADENA CABALLERO EN ACERO', NULL, 'Tienda'),
('JOYERÍA', 'COLLAR ABEJA', NULL, 'Tienda'),
('JOYERÍA', 'COLLAR CEREZO', 6, 'Bodega'),
('JOYERÍA', 'COLLAR CORAZON AZUL', 3, 'Bodega'),
('JOYERÍA', 'COLLAR FLOR MARGARRITA', 5, 'Bodega'),
('JOYERÍA', 'COLLAR FRESA-PLATA 925', 11, 'Bodega'),
('JOYERÍA', 'COLLAR LEDY DI', NULL, 'Tienda'),
('JOYERÍA', 'COLLAR LUCIRNAGA LUMINOSO', NULL, 'Tienda'),
('JOYERÍA', 'COLLAR MARGARITA- ABEJA ORO 14K', 3, 'Bodega'),
('JOYERÍA', 'COLLAR MASCOTA', 6, 'Bodega'),
('JOYERÍA', 'COLLAR MASCOTA ENCHAPADO ORO 14K', 6, 'Bodega'),
('JOYERÍA', 'COLLAR TULIPAN ENCHAPADO ORO 14K', 7, 'Bodega'),
('JOYERÍA', 'PULSERA CABALLERO EN ACERO', NULL, 'Tienda'),
('JOYERÍA', 'PULSERA HELLO KITTY - ENCHAPADO ORO 14K', 25, 'Bodega'),
('JOYERÍA', 'PULSERA HELLO KITTY ENCHAPADO PLATA 925', 1, 'Bodega'),
('JOYERÍA', 'PULSERA MARGARITA-PLATA 925', NULL, 'Tienda'),
('JOYERÍA', 'PULSERA PLATA CORAZON ELÁSTICA', NULL, 'Tienda'),
('JOYERÍA', 'PULSERA ROSA PLATA 925', 5, 'Bodega'),
('MASCOTAS', 'MANGUERA PARA PERROS', 19, 'Bodega'),
('RELOJES', 'RELOJ DIGITAL HOMBRE SKMEI', 10, 'Bodega'),
('RELOJES', 'RELOJ HOMBRE SPIDERMAN CUERO', 12, 'Bodega'),
('RELOJES', 'RELOJ INFANTIL CON MUSICA', 32, 'Bodega'),
('RELOJES', 'RELOJ MUJER BRAZALETE ACERO HELLO KITTY', 17, 'Bodega'),
('RELOJES', 'RELOJ MUJER CON PULSERA HELLO KITTY', 5, 'Bodega'),
('RELOJES', 'RELOJ MUJER STICH ACERO', 6, 'Bodega'),
('RELOJES', 'RELOJ MUJER STICH CUERO', 18, 'Bodega'),
('SEGURIDAD', 'CÁMARA SEGURIDAD WI-FI EXTERIOR E INTERIOR', 2, 'Bodega'),
('SEGURIDAD', 'CÁMARA SEGURIDAD WI-FI SOLAR', 4, 'Bodega'),
('USO PERSONAL', 'CEPILLO DE BAÑO', 16, 'Bodega'),
('USO PERSONAL', 'CEPILLO FACIAL', 4, 'Bodega'),
('USO PERSONAL', 'COLAS DE CABELLO NIÑA', 22, 'Bodega'),
('USO PERSONAL', 'CORRECTOR DE JUANETE', 28, 'Bodega'),
('USO PERSONAL', 'CREMAS KARSELL CABELLO', 30, 'Bodega'),
('USO PERSONAL', 'DEPILADOR LASER', 14, 'Bodega'),
('USO PERSONAL', 'GUANTE DE COMPRESIÓN', 29, 'Bodega'),
('USO PERSONAL', 'KIT DEPILADOR LASER Y DEPILADOR MANUAL Y CEPILLO FACIAL', NULL, 'Tienda'),
('USO PERSONAL', 'MASAJEADOR FACIAL', 9, 'Bodega'),
('USO PERSONAL', 'MEDIDOR DE PRESIÓN ARTERIAL', 9, 'Bodega'),
('VARIOS', 'LONA PARA PLAYA', 23, 'Bodega'),
('VARIOS', 'SOPORTE DE BICICLETA', 15, 'Bodega'),
('VESTIMENTA', 'CHAQUETA BOB ESPONJA CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA CAPUCHA SNOOPY AMIGOS CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA CAPUCHA SNOOPY CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA GARFRIEL CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA HELLO KITTY CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA LOONEY TUNES CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MICKEY Y MINI LONDRES CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE VARIOS CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE COCA COLA CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE NEGRA CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MICKEY MOUSE NEGRA Y GRIS CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA MINI MAUSE CELESTE CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA OSOS ESCANDALOSOS CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA RUGRATS AMIGOS CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA SONIC CORTA VIENTOS NIÑOS 2 A 8 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA SPIDERMAN CORTA VIENTOS NIÑOS 2 A 12 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA SPIDERMAN CORTA VIENTOS NIÑOS 2 A 8 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA STITCH- CELESTE CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA STITCH- ROSA CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'CHAQUETA STITCH- TORNASOL CORTA VIENTOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER ANGEL CAPUCHA CON DETALLE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER ARISTOCATS NIÑA 6 A 12 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER BUGS BUNNY', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER CAPUCHA SNOOPY ALGODÓN', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER CARLITOS OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER GOOFY NINOS 6 A 12 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO CHARLI OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO KITTY CAPUCHA CON DETALLE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO KITTY OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO KITTY PELUDITO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO KITTY PERSONAJES OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO PATO DONALD OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER HELLO STITCH OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER JIGGLYPUFF CAPUCHA CON DETALLE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER KUROMORI CAPUCHA CON DETALLE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER KUROMORI OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MAFALDA CAPUCHA CON DETALLE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MAFALDA PELUDITO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MELODI CAPUCHA CON DETALLE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE HISTORIA', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE HISTORIA NINOS 4 A 12 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE PELUDITO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE PELUDITO VARIOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE SALUDOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MICKEY MOUSE SIN CAPUCHA', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELUDITO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELUDITO LAZO ROJO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MINI MOUSE CAPUCHA PELUDITO MORADO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MINI MOUSE NIÑA 4 A 12 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MINNI OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER MOSTER IN OVERSIZE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER NARUTO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER OSOS ESCANDALOSOS ALGODÓN', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER OSOS ESCANDALOSOS NIÑOS 2 A 8 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER PANTERA ROSA PELUDITO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER PIKACHU CAPUCHA CON DETALLE', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER RUGRATS AMIGOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER RUGRATS AMIGOS NINOS 6 A 12 AÑOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER RUGRATS ANGELICA', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER RUGRATS ANGELICA CAPUCHA PELUDITA', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER RUGRATS CARLITOS', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER STITCH CAPUCHA ALGODÓN', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER STITCH CUELLO REDONDO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER STITCH PELUDITO', NULL, 'Tienda'),
('VESTIMENTA', 'SUETER WINNIE POOH CAPUCHA PELIDITA', NULL, 'Tienda'),
('VESTIMENTA', 'SUTER HELLO KITTY PELUDITO NEGRO', NULL, 'Tienda'),
('VESTIMENTA', 'SUTER TOM Y JERRY', NULL, 'Tienda');

go


INSERT INTO [dbo].[Movimientos]
           ([MvmIdProducto]
           ,[MvmCantidad]
           ,[MvmFecha]
           ,[MvmIdMotivoMovimiento]
           ,[MvmIdUsuario]
           ,[MvmIdBodega])
SELECT 
    P.PrdId,
    I.SumaCantidadTienda,
    GETDATE(),
    1,
    1,
    CASE
        WHEN I.Sitio = 'Tienda' THEN 1
        ELSE 2
    END
FROM [dbo].[Productos] P
INNER JOIN #Inventario I ON P.PrdNombre = I.DescripcionArticulo
INNER JOIN TipoProducto TP ON P.PrdIdTipoProducto = TP.TppId AND TP.TppDescripcion = I.Categoria
WHERE I.SumaCantidadTienda IS NOT NULL
AND NOT EXISTS (
    SELECT 1
    FROM [dbo].[Movimientos] M
    WHERE M.MvmIdProducto = P.PrdId
    AND M.MvmCantidad = I.SumaCantidadTienda
    AND M.MvmFecha = CAST(GETDATE() AS DATE)  -- Opcional: verifica la fecha si es necesario
);

